FROM node:20-alpine AS builder
WORKDIR /app
ARG APP_PATH
ARG VITE_PUBLIC_API_URL
ARG VITE_ADMIN_API_URL
ENV VITE_PUBLIC_API_URL=$VITE_PUBLIC_API_URL
ENV VITE_ADMIN_API_URL=$VITE_ADMIN_API_URL
COPY package*.json ./
COPY ${APP_PATH}/package*.json ./${APP_PATH}/
RUN npm install
COPY ${APP_PATH} ./${APP_PATH}
WORKDIR /app/${APP_PATH}
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/${APP_PATH}/dist /usr/share/nginx/html
COPY infrastructure/docker/nginx-spa.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
