FROM node:20-alpine
WORKDIR /app
ARG APP_PATH
COPY package*.json ./
COPY ${APP_PATH}/package*.json ./${APP_PATH}/
RUN npm install
COPY ${APP_PATH} ./${APP_PATH}
WORKDIR /app/${APP_PATH}
EXPOSE 4000
CMD ["npm", "start"]
