import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useParams } from 'react-router-dom';
import './styles.css';

const API = import.meta.env.VITE_PUBLIC_API_URL || 'http://localhost:4000';
const nav = [['About','/about'],['Admissions','/admissions'],['Programs','/programs'],['Workshops','/workshops'],['Events','/events'],['Announcements','/announcements'],['Student Activities','/student-activities']];
async function api(path){ const r = await fetch(`${API}${path}`); if(!r.ok) throw new Error('Request failed'); return r.json(); }
function useApi(path, fallback){ const [data,setData]=useState(fallback); const [err,setErr]=useState(''); useEffect(()=>{ let live=true; api(path).then(x=>live&&setData(x)).catch(e=>live&&setErr(e.message)); return()=>{live=false};},[path]); return {data,err}; }
const fmt = (d) => d ? new Intl.DateTimeFormat('en',{year:'numeric',month:'long',day:'numeric'}).format(new Date(d)) : '';

function Nav(){ const [open,setOpen]=useState(false); return <header className="nav"><Link className="brand" to="/"><span>A</span><b>Aurum<br/><small>Bilingual School</small></b></Link><button className="hamb" onClick={()=>setOpen(!open)}>☰</button><div className={open?'links open':'links'}>{nav.map(([l,h])=><NavLink key={h} to={h} onClick={()=>setOpen(false)}>{l}</NavLink>)}</div></header>; }
function Footer(){ return <footer><div><h3>Aurum Bilingual School</h3><p>Academic excellence, practical learning, bilingual confidence, and strong character.</p></div><p>Email: info@aurumschool.com<br/>Website: aurumschool.com</p></footer>; }
function Card({item,base,date='published_at'}){ return <article className="card">{item.cover_image?.publicUrl?<img src={item.cover_image.publicUrl} alt={item.title}/>:<div className="ph">{item.title?.[0]}</div>}<div><small>{fmt(item[date])}</small><h3>{item.title}</h3><p>{item.summary || item.description || item.body}</p>{base&&<Link to={`${base}/${item.slug}`}>Read more</Link>}</div></article>; }
function Home(){ const {data}=useApi('/api/home',{events:[],announcements:[],workshops:[],activities:[]}); return <><section className="hero"><div><p className="eye">Welcome to</p><h1>Aurum Bilingual School</h1><p>Building academic confidence, practical skills, bilingual communication, and strong character.</p><Link className="btn" to="/admissions">Start Admissions</Link></div><aside><b>Learn</b><b>Build</b><b>Lead</b></aside></section><section className="split"><div><p className="eye">Our Mission</p><h2>Developing confident learners with practical ability.</h2><p>Aurum prepares students through academics, values, practical workshops, and student activities.</p></div><div className="box"><p className="eye">Motto</p><h2>Learn. Build. Lead.</h2></div></section><Section title="Latest Workshops" items={data.workshops}/><section className="section tint"><h2>Events and Announcements</h2>{[...data.announcements,...data.events].map(x=><Link className="row" key={x.id} to={`${x.event_date?'/events':'/announcements'}/${x.slug}`}>{x.title}</Link>)}</section><Section title="Student Activities" items={data.activities} base="/student-activities" date="activity_date"/></>; }
function Section({title,items,base,date}){ return <section className="section"><h2>{title}</h2><div className="grid">{items.map(i=><Card key={i.id} item={i} base={base} date={date}/>)}</div></section>; }
function StaticPage({title,children}){ return <section className="page"><p className="eye">Aurum Bilingual School</p><h1>{title}</h1>{children}</section>; }
function About(){ return <StaticPage title="About Aurum"><p>Aurum Bilingual School provides a structured learning environment where classroom education is supported by practical projects, student activities, discipline, and parent communication.</p></StaticPage>; }
function Admissions(){ return <StaticPage title="Admissions"><h2>Requirements</h2><ul><li>Application form</li><li>Birth certificate or ID</li><li>Previous school record where applicable</li><li>Parent or guardian contact details</li></ul><h2>Process</h2><ol><li>Contact the school.</li><li>Submit documents.</li><li>Complete review and placement discussion.</li><li>Receive confirmation.</li></ol></StaticPage>; }
function Programs(){ return <StaticPage title="Programs"><p>Programs include academic learning, bilingual communication, practical skills, student activities, leadership, and character development.</p></StaticPage>; }
function Workshops(){ const {data}=useApi('/api/workshops',[]); return <StaticPage title="Workshops"><div className="grid">{data.map(i=><Card key={i.id} item={i}/>)}</div></StaticPage>; }
function Events(){ const {data}=useApi('/api/events',[]); return <StaticPage title="Events"><div className="grid">{data.map(i=><Card key={i.id} item={i} base="/events" date="event_date"/>)}</div></StaticPage>; }
function Announcements(){ const {data}=useApi('/api/announcements',[]); return <StaticPage title="Announcements"><div className="grid">{data.map(i=><Card key={i.id} item={i} base="/announcements"/>)}</div></StaticPage>; }
function Activities(){ const {data}=useApi('/api/student-activities',[]); return <StaticPage title="Student Activities"><div className="grid">{data.map(i=><Card key={i.id} item={i} base="/student-activities" date="activity_date"/>)}</div></StaticPage>; }
function Detail({type}){ const {slug}=useParams(); const {data}=useApi(`/api/${type}/${slug}`,null); if(!data) return <section className="page">Loading...</section>; return <article className="page"><p className="eye">{fmt(data.event_date || data.activity_date || data.published_at)}</p><h1>{data.title}</h1>{data.cover_image?.publicUrl&&<img className="detail" src={data.cover_image.publicUrl} alt={data.title}/>}<p>{data.body}</p>{data.images?.length>0&&<div className="gallery">{data.images.map(img=><img key={img.id} src={img.public_url}/>)}</div>}{data.videos?.map(v=><a className="row" key={v.id} href={v.video_url} target="_blank">{v.title||v.video_url}</a>)}</article>; }
function App(){ return <><Nav/><main><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/admissions" element={<Admissions/>}/><Route path="/programs" element={<Programs/>}/><Route path="/workshops" element={<Workshops/>}/><Route path="/events" element={<Events/>}/><Route path="/events/:slug" element={<Detail type="events"/>}/><Route path="/announcements" element={<Announcements/>}/><Route path="/announcements/:slug" element={<Detail type="announcements"/>}/><Route path="/student-activities" element={<Activities/>}/><Route path="/student-activities/:slug" element={<Detail type="student-activities"/>}/></Routes></main><Footer/></>; }

ReactDOM.createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
